//
// (C) 2010 株式会社ジャストシステム
//
// ***** DO NOT EDIT THIS FILE *****

var lat = new Array(1);
var lng = new Array(1);
var markerwindowinfo = new Array(1);
var markerwindowopen = new Array(1);
var markerevent = new Array(1);
var firstshown = new Array(1);
lat[0] = "36.728463";
lng[0] = "140.002175";
markerwindowinfo[0] = "ＤＫＳ喜連川事業所";
markerwindowopen[0] = "1";
markerevent[0] = "mouseover";
firstshown[0] = "1";

function createMarker(point, event, info, open) {
	var marker = new GMarker(point);
	if(open == 1){
		GEvent.addListener(marker, event, function() {
			marker.openInfoWindowHtml(info);
		});
	}
	return marker;
}

function hpbmaponload() {
  if (GBrowserIsCompatible()) {
	var map = new GMap2(document.getElementById("HPBMAP_20110712055040"));
	map.addControl(new GMapTypeControl());
	map.addControl(new GSmallMapControl());
	map.setCenter(new GLatLng(36.731593, 140.002213), 14);
	map.setMapType(G_NORMAL_MAP);
	for (var i = 0; i < 1; i++) {
	  if(firstshown[i] == 1){
		var point = new GLatLng(lat[i], lng[i]);
		var marker = new GMarker(point);
		map.addOverlay(createMarker(point, markerevent[i], markerwindowinfo[i], markerwindowopen[i]));
	  }
	}
	return map;
  }
}